name: Use the data

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run'
    outputs:
      pr_number: ${{ steps.pr_output.outputs.pr_number }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip pr_number.zip

      - name: 'make env var'
        id: 'pr_output'
        run: |
          cat ./pr_number
          echo "pr_number=$(cat ./pr_number)" >> "GITHUB_OUTPUT"

  secondjob:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - env:
          PR_NUMBER: ${{needs.download.outputs.pr_number}}
        run: echo "PR_NUMBER"