name: Has PR do-not-merge label
on:
  pull_request: {}

jobs:
  do-not-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - if: contains(github.event.pull_request.labels.*.name, 'pr/do-not-merge')
      run: exit 1
