name: Has PR do-not-merge label
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  do-not-merge:
    if: contains(github.event.pull_request.labels.*.name, 'pr/do-not-merge')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - run: exit 1
  otherwise:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0
