name: contributer-badge
on:
  workflow_dispatch: {}
  workflow_run:
    workflows:
      - pr-linter-trigger
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  call-action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: kaizencc/github-merit-badger@main
        id: badger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          badges: '[a,b,c]'
          thresholds: '[0,1,2]'
          badge-type: 'achievement'
          ignore-usernames: '[Tianyi-W,dependabot[bot]]'
      # - uses: kaizencc/github-merit-badger@main
      #   id: contributor-badge-hotlist
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     badges: '[1 :trophy:,top 3 :fire:,top 5 :sunglasses:]'
      #     thresholds: '[1,2,3]'
      #     badge-type: 'leaderboard'
